before_install:
  - sudo apt-get -y install openssl libssl-dev libsqlite3-dev sqlite3
addons:
  apt:
    update: true

language: c
compiler:
  - gcc
  - clang
os:
  - linux
script:
 - cd Debug
 - make clean && make all
